import { useState } from 'react';

/**
 * Premium unlock modal for pitch access
 */
export default function UnlockModal({ isOpen, onClose, onUnlock, price = '1 credit' }) {
  const [isConfirming, setIsConfirming] = useState(false);

  if (!isOpen) return null;

  const handleConfirm = async () => {
    setIsConfirming(true);
    // Simulate processing
    setTimeout(() => {
      onUnlock();
      setIsConfirming(false);
      onClose();
    }, 1500);
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-slate-950/95 backdrop-blur-md rounded-xl border border-slate-800/50 w-full max-w-md overflow-hidden">
        {/* Header */}
        <div className="p-6 border-b border-slate-800/50">
          <div className="flex items-center space-x-3 mb-4">
            <div className="w-12 h-12 bg-gradient-to-br from-purple-500/20 to-cyan-500/20 rounded-xl flex items-center justify-center">
              <span className="text-2xl">🔓</span>
            </div>
            <div>
              <h3 className="text-white font-bold text-xl">Unlock Custom Pitch</h3>
              <p className="text-slate-400 text-sm">Generated by AI agents</p>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="p-6">
          <div className="text-center mb-6">
            <div className="text-4xl font-bold text-white mb-2">{price}</div>
            <p className="text-slate-400">One-time unlock fee</p>
          </div>

          <div className="bg-slate-900/50 rounded-lg p-4 mb-6">
            <h4 className="text-white font-medium mb-2">What you'll get:</h4>
            <ul className="text-slate-300 text-sm space-y-1">
              <li>• Personalized sales pitch</li>
              <li>• AI-optimized messaging</li>
              <li>• Copy-paste ready content</li>
              <li>• Multiple outreach templates</li>
            </ul>
          </div>

          <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-4 mb-6">
            <p className="text-amber-300 text-sm">
              💡 This pitch was crafted specifically for this lead's intent signals and pain points.
            </p>
          </div>
        </div>

        {/* Actions */}
        <div className="px-6 pb-6 flex space-x-3">
          <button
            onClick={onClose}
            className="flex-1 px-4 py-3 bg-slate-800/50 hover:bg-slate-700/50 text-slate-300 hover:text-white rounded-lg transition-colors"
            disabled={isConfirming}
          >
            Cancel
          </button>
          <button
            onClick={handleConfirm}
            disabled={isConfirming}
            className="flex-1 px-4 py-3 bg-gradient-to-r from-purple-500 to-cyan-500 hover:from-purple-600 hover:to-cyan-600 text-white font-semibold rounded-lg transition-all duration-200 transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isConfirming ? (
              <div className="flex items-center justify-center space-x-2">
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                <span>Unlocking...</span>
              </div>
            ) : (
              'Unlock Pitch'
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
